import {
  FaBan,
  FaArrowLeft,
  FaArrowRight,
  FaEye,
  FaSearchPlus,
  FaSyncAlt,
  FaExpandAlt,
  FaMeteor,
  FaArrowDown,
  FaArrowUp,
  FaBolt,
  FaAngleDoubleDown,
  FaAngleDoubleRight,
  FaLayerGroup,
  FaMagic,
  FaCubes,
} from "react-icons/fa";
export const transitionOptions = [
  { name: "None", key: "none", Icon: FaBan },
  { name: "Cross Dissolve", key: "crossDissolve", Icon: FaEye },
  { name: "Dip to Black", key: "dipToBlack", Icon: FaArrowDown },
  { name: "Dip to White", key: "dipToWhite", Icon: FaArrowUp },
  { name: "Film Dissolve", key: "filmDissolve", Icon: FaSyncAlt },
  { name: "Wipe Left to Right", key: "wipeLeftToRight", Icon: FaArrowRight },
  { name: "Wipe Top to Bottom", key: "wipeTopToBottom", Icon: FaArrowDown },
  { name: "Slide In", key: "slideIn", Icon: FaArrowLeft },
  { name: "Push", key: "push", Icon: FaExpandAlt },
  { name: "Zoom", key: "zoom", Icon: FaSearchPlus },
  { name: "Morph Cut", key: "morphCut", Icon: FaMeteor },

  { name: "Fade In", key: "fadeIn", Icon: FaBolt },
  { name: "Slide Up", key: "slideUp", Icon: FaAngleDoubleDown },
  { name: "Slide Right", key: "slideRight", Icon: FaAngleDoubleRight },
  { name: "Flip In", key: "flipIn", Icon: FaLayerGroup },
  { name: "Blur In", key: "blurIn", Icon: FaMagic },
  { name: "Scale In", key: "scaleIn", Icon: FaCubes },
];
